name: .NET Build and Publish Workflow

on:
  push:
    branches: ['master', 'main']
  pull_request:
    branches:
    - main
    - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: Setup .NET
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore
    - run: dotnet restore
    
    - name: Build
    - run: dotnet build --configuration Release --no-restore

    - name: Publish
    - run: dotnet publish --output ./Publish --configuration Release --no-build
